// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	stocks "testify-tutorial/stocks"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// PriceProvider is an autogenerated mock type for the PriceProvider type
type PriceProvider struct {
	mock.Mock
}

// Latest provides a mock function with given fields:
func (_m *PriceProvider) Latest() (*stocks.PriceData, error) {
	ret := _m.Called()

	var r0 *stocks.PriceData
	if rf, ok := ret.Get(0).(func() *stocks.PriceData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stocks.PriceData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: date
func (_m *PriceProvider) List(date time.Time) ([]*stocks.PriceData, error) {
	ret := _m.Called(date)

	var r0 []*stocks.PriceData
	if rf, ok := ret.Get(0).(func(time.Time) []*stocks.PriceData); ok {
		r0 = rf(date)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*stocks.PriceData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = rf(date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
